#!/usr/bin/env python

import sys
import numpy as np
from scipy.io import netcdf_file

print()
print("Usage:", __file__, "regcoil_out.<extension>")

filename = sys.argv[1]
f = netcdf_file(filename, mmap=False)
r_plasma = f.variables["r_plasma"][()]
r_coil = f.variables["r_coil"][()]
#ntheta_coil = f.variables["ntheta_coil"][()]
#nzeta_coil = f.variables["nzeta_coil"][()]
#normal_coil = f.variables["normal_coil"][()]
#norm_normal_coil = f.variables["norm_normal_coil"][()]

print("r_plasma.shape:", r_plasma.shape)
#exit(0)

from mayavi import mlab

fig = mlab.figure(bgcolor=(1,1,1), size=(2560, 1600))

mlab.mesh(r_plasma[:, :, 0],
          r_plasma[:, :, 1],
          r_plasma[:, :, 2],
          color=(1,0,0))

mlab.mesh(r_coil[:, :, 0],
          r_coil[:, :, 1],
          r_coil[:, :, 2],
          color=(0, 0, 1),
          representation="wireframe"
          )

"""
delta = 0.1
r = np.zeros((3, 2))
for jtheta in range(ntheta_coil):
    for jzeta in range(nzeta_coil):
        r[:, 0] = r_coil[jtheta, jzeta, :]
        r[:, 1] = r[:, 0] + delta * normal_coil[jtheta, jzeta, :] / norm_normal_coil[jtheta, jzeta]
        mlab.plot(r[0, :], r[1, :], r[2, :], color=(0, 0.7, 0))
"""

#mlab.mesh(r_coil[:, :, 0],
#          r_coil[:, :, 1],
#          r_coil[:, :, 2],
#          opacity=0.5)

fig.scene.camera.zoom(1.5)
mlab.show()
