"""Unit tests for the `Surface` / `FourierSurface` object model."""

from pathlib import Path

import numpy as np
import pytest

from regcoil import CoilSurface, FourierSurface, PlasmaSurface
from regcoil.surface import Surface

REPO_ROOT = Path(__file__).resolve().parents[2]
EQUILIBRIA = REPO_ROOT / "equilibria"

# Reference area, volume, minor_radius, major_radius, aspect_ratio (VMEC/simsopt
# definitions) for two VMEC boundary surfaces, at ntheta=nzeta=128. These were
# generated by regcoil and independently confirmed to match simsopt's
# `SurfaceRZFourier.{area,volume,minor_radius,major_radius,aspect_ratio}` to
# ~1e-15 (see `test_radii_match_simsopt`); hard-coded here so the check still
# runs when simsopt is not installed. LandremanSenguptaPlunk_section5p3 is *not*
# stellarator-symmetric, exercising the non-stellsym path.
RADII_REFERENCE = {
    "wout_li383_1.4m.nc": dict(
        area=24.51949746023836,
        volume=2.9787172145367085,
        minor_radius=0.3257591684215119,
        major_radius=1.422021749477235,
        aspect_ratio=4.3652547259613215,
    ),
    "wout_LandremanSenguptaPlunk_section5p3_reference.nc": dict(
        area=4.646433515031652,
        volume=0.19922832630312443,
        minor_radius=0.10046480101808615,
        major_radius=0.9999850071431668,
        aspect_ratio=9.953585703744587,
    ),
}


def test_evaluate_hand_checked_case():
    """A 2-mode surface (m=0,n=0 and m=1,n=2 with nfp=2), hand-evaluated at
    three (theta, zetal) points; see the derivation in the PR description.
    """
    xm = [0, 1]
    xn = [0, 2]
    rmnc = [5.0, 1.0]
    rmns = [0.0, 0.5]
    zmnc = [0.0, 0.2]
    zmns = [0.0, 0.3]
    surf = FourierSurface(xm, xn, rmnc, zmns, rmns, zmnc, nfp=2, ntheta=2, nzeta=1)

    theta = np.array([0.0, np.pi / 2])
    zetal = np.array([0.0, np.pi / 2])
    result = surf._evaluate(theta, zetal)
    r = result["r"]
    drdtheta = result["drdtheta"]
    drdzeta = result["drdzeta"]

    # (theta=0, zetal=0): R=6, Z=0.2, phi=0 -> (6, 0, 0.2)
    np.testing.assert_allclose(r[:, 0, 0], [6.0, 0.0, 0.2], atol=1e-12)
    # (theta=pi/2, zetal=0): R=5.5, Z=0.3, phi=0 -> (5.5, 0, 0.3)
    np.testing.assert_allclose(r[:, 1, 0], [5.5, 0.0, 0.3], atol=1e-12)
    # (theta=0, zetal=pi/2): R=4, Z=-0.2, phi=pi/2 -> (0, 4, -0.2)
    np.testing.assert_allclose(r[:, 0, 1], [0.0, 4.0, -0.2], atol=1e-12)

    # Derivatives at (theta=0, zetal=0), hand-derived.
    np.testing.assert_allclose(drdtheta[:, 0, 0], [0.5, 0.0, 0.3], atol=1e-12)
    np.testing.assert_allclose(drdzeta[:, 0, 0], [-1.0, 6.0, -0.6], atol=1e-12)


def test_xn_must_be_multiple_of_nfp():
    """xn includes the factor of nfp (VMEC convention); reject inconsistent input."""
    with pytest.raises(ValueError):
        FourierSurface([1], [1], [1.0], [0.0], nfp=3)


def test_stellarator_symmetric_inferred():
    surf = FourierSurface([0, 1], [0, 0], [1.0, 0.5], [0.0, 0.5], nfp=1)
    assert surf.stellarator_symmetric

    surf2 = FourierSurface([0, 1], [0, 0], [1.0, 0.5], [0.0, 0.5], rmns=[0.0, 0.1], nfp=1)
    assert not surf2.stellarator_symmetric

    # A cosine-parity nu mode (numnc) also breaks stellarator symmetry.
    surf3 = FourierSurface([0, 1], [0, 0], [1.0, 0.5], [0.0, 0.5], numnc=[0.0, 0.1], nfp=1)
    assert not surf3.stellarator_symmetric


def test_nu_angle_shift_places_point_at_zeta_plus_nu():
    """With a single nu mode, the physical toroidal angle is phi = zeta + nu,
    so x = R*cos(zeta + nu), y = R*sin(zeta + nu). Hand-check at a point where
    the shift is nonzero, and confirm the analytic derivatives match finite
    differences."""
    # nu = 0.1 * sin(theta) (m=1, n=0), R = 5 + cos(theta), Z = sin(theta).
    xm, xn = [0, 1], [0, 0]
    surf = FourierSurface(
        xm, xn, rmnc=[5.0, 1.0], zmns=[0.0, 1.0], numns=[0.0, 0.1],
        nfp=1, standard_toroidal_angle=False,
    )
    theta = np.array([0.7])
    zetal = np.array([0.4])
    out = surf._evaluate(theta, zetal)
    R = 5.0 + np.cos(0.7)
    nu = 0.1 * np.sin(0.7)
    phi = 0.4 + nu
    np.testing.assert_allclose(out["r"][:, 0, 0], [R * np.cos(phi), R * np.sin(phi), np.sin(0.7)], atol=1e-12)

    # Analytic vs finite-difference derivatives on a small grid.
    th = np.array([0.3, 1.9, 4.0])
    ze = np.array([0.2, 2.1, 5.0])
    h = 1e-6
    base = surf._evaluate(th, ze)
    fd_dth = (surf._evaluate(th + h, ze)["r"] - surf._evaluate(th - h, ze)["r"]) / (2 * h)
    fd_dze = (surf._evaluate(th, ze + h)["r"] - surf._evaluate(th, ze - h)["r"]) / (2 * h)
    np.testing.assert_allclose(base["drdtheta"], fd_dth, atol=1e-7)
    np.testing.assert_allclose(base["drdzeta"], fd_dze, atol=1e-7)


def test_nu_zero_reduces_to_standard_surface():
    """A FourierSurface with no nu modes evaluates identically whether or not
    the (unused) nu branch would run -- i.e. nu defaults to the phi=zeta fast
    path and standard_toroidal_angle is True."""
    surf = FourierSurface([0, 1, 1], [0, 0, 2], [5.0, 1.0, 0.1], [0.0, 1.0, 0.1], nfp=2)
    assert surf.standard_toroidal_angle is True
    assert np.all(surf.numns == 0) and np.all(surf.numnc == 0)


def test_standard_toroidal_angle_defaults_true():
    """Every plain Fourier-coefficient construction represents its `zeta` as
    the standard toroidal angle; only `CoilSurface.from_uniform_offset`'s
    normal-offset method (default) sets this False."""
    surf = FourierSurface([0, 1], [0, 0], [1.0, 0.5], [0.0, 0.5], nfp=1)
    assert surf.standard_toroidal_angle is True

    surf2 = FourierSurface([0, 1], [0, 0], [1.0, 0.5], [0.0, 0.5], nfp=1, standard_toroidal_angle=False)
    assert surf2.standard_toroidal_angle is False


def test_circular_torus_area_and_shape():
    R0, a, nfp = 5.0, 1.2, 3
    torus = FourierSurface.circular_torus(R0=R0, a=a, nfp=nfp, ntheta=32, nzeta=24)

    assert torus.nfp == nfp
    assert torus.stellarator_symmetric
    np.testing.assert_allclose(torus.area, 4 * np.pi**2 * R0 * a, rtol=1e-12)

    # R, Z on the theta grid at zeta=0 match the standard circular-cross-section formula.
    theta = torus.theta
    R = np.sqrt(torus.r[0, :, 0] ** 2 + torus.r[1, :, 0] ** 2)
    Z = torus.r[2, :, 0]
    np.testing.assert_allclose(R, R0 + a * np.cos(theta), atol=1e-12)
    np.testing.assert_allclose(Z, a * np.sin(theta), atol=1e-12)

    # The volume formula is a spectral quadrature (periodic trapezoid rule
    # applied to a smooth periodic integrand, using the analytic dZ/dtheta),
    # so it should match the analytic volume 2*pi^2*R0*a^2 to near machine
    # precision even at modest resolution.
    exact = 2 * np.pi**2 * R0 * a**2
    np.testing.assert_allclose(torus.volume, exact, rtol=1e-12)


def _circular_torus_modes(R0, a, nfp, nu_modes=None):
    """Fourier modes for a circular-cross-section torus, optionally with extra
    `nu` (toroidal-angle-shift) modes appended. Returns kwargs for
    `FourierSurface`. The nu modes reparameterize the toroidal angle without
    moving any physical point, so all geometric scalars are unchanged."""
    xm = [0, 1]
    xn = [0, 0]
    rmnc = [R0, a]
    zmns = [0.0, a]
    numns = [0.0, 0.0]
    if nu_modes:
        for m, n, val in nu_modes:
            xm.append(m)
            xn.append(n * nfp)  # xn carries the factor of nfp (VMEC convention)
            rmnc.append(0.0)
            zmns.append(0.0)
            numns.append(val)
    return dict(xm=xm, xn=xn, rmnc=rmnc, zmns=zmns, numns=numns)


def test_torus_radii_match_analytic():
    """For a circular-cross-section torus, minor_radius = a, major_radius = R0,
    aspect_ratio = R0/a exactly (these VMEC definitions are exact for a
    circular torus regardless of grid resolution)."""
    R0, a, nfp = 5.0, 1.2, 3
    torus = FourierSurface(
        **_circular_torus_modes(R0, a, nfp), nfp=nfp, ntheta=64, nzeta=48
    )
    assert torus.standard_toroidal_angle
    np.testing.assert_allclose(torus.minor_radius, a, rtol=1e-12)
    np.testing.assert_allclose(torus.major_radius, R0, rtol=1e-12)
    np.testing.assert_allclose(torus.aspect_ratio, R0 / a, rtol=1e-12)


def test_torus_radii_match_analytic_nonzero_nu():
    """The same circular torus, but described with a nonzero `nu` (so `zeta` is
    not the physical toroidal angle). minor/major/aspect are properties of the
    physical surface, so they must be unchanged by this reparameterization --
    minor_radius = a, major_radius = R0, aspect_ratio = R0/a still hold
    exactly. This checks that both `mean_cross_sectional_area` (via its
    Jacobian change of variables) and `volume` (via its coordinate-free form)
    are correct when zeta != phi."""
    R0, a, nfp = 5.0, 1.2, 3
    nu_modes = [(0, 1, 0.15), (1, 1, 0.07)]  # (m, n, numns) modes
    torus = FourierSurface(
        **_circular_torus_modes(R0, a, nfp, nu_modes),
        nfp=nfp, ntheta=128, nzeta=128, standard_toroidal_angle=False,
    )
    assert not torus.standard_toroidal_angle
    assert np.any(torus.numns != 0)
    np.testing.assert_allclose(torus.minor_radius, a, rtol=1e-12)
    np.testing.assert_allclose(torus.major_radius, R0, rtol=1e-12)
    np.testing.assert_allclose(torus.aspect_ratio, R0 / a, rtol=1e-12)


@pytest.mark.parametrize("wout", list(RADII_REFERENCE))
def test_radii_match_reference_values(wout):
    """area, volume, minor_radius, major_radius, aspect_ratio for the li383 and
    LandremanSenguptaPlunk_section5p3 (non-stellarator-symmetric) VMEC
    boundaries match hard-coded reference values (equal to simsopt's, but
    checkable without simsopt installed)."""

    plasma = PlasmaSurface.from_wout(str(EQUILIBRIA / wout), ntheta=128, nzeta=128)
    for name, ref in RADII_REFERENCE[wout].items():
        np.testing.assert_allclose(getattr(plasma, name), ref, rtol=1e-11)


@pytest.mark.parametrize("wout", list(RADII_REFERENCE))
def test_radii_match_simsopt(wout):
    """Same two boundaries, compared directly against simsopt's
    `SurfaceRZFourier.{area,volume,minor_radius,major_radius,aspect_ratio}`.
    Skipped if simsopt is not installed; `test_radii_match_reference_values`
    covers the no-simsopt case with the same numbers."""
    pytest.importorskip("simsopt")
    from simsopt.geo import SurfaceRZFourier

    path = str(EQUILIBRIA / wout)
    plasma = PlasmaSurface.from_wout(path, ntheta=128, nzeta=128)
    ss = SurfaceRZFourier.from_wout(path, nphi=128, ntheta=128, range="field period")
    # simsopt's volume is signed; compare magnitudes.
    np.testing.assert_allclose(plasma.area, ss.area(), rtol=1e-10)
    np.testing.assert_allclose(plasma.volume, abs(ss.volume()), rtol=1e-10)
    np.testing.assert_allclose(plasma.minor_radius, ss.minor_radius(), rtol=1e-10)
    np.testing.assert_allclose(plasma.major_radius, ss.major_radius(), rtol=1e-10)
    np.testing.assert_allclose(plasma.aspect_ratio, ss.aspect_ratio(), rtol=1e-10)


def test_radii_3d_nonzero_nu_match_cross_section_pipeline():
    """Fully 3D surface with nonzero `nu`: the uniform-offset coil surface
    (`standard_toroidal_angle=False`), whose `zeta` is genuinely not the
    physical toroidal angle. There is no analytic answer here, so cross-check
    minor/major/aspect against a completely independent geometric pipeline that
    works in the *physical* toroidal angle phi: sample true constant-phi cross
    sections via `cross_section(phi)`, then get each cross-sectional area and
    the enclosed volume by polygon (Green's-theorem) integration. Agreement is
    limited by the linear interpolation in `cross_section`, hence the ~3e-3
    tolerance."""

    plasma = PlasmaSurface.from_wout(
        str(EQUILIBRIA / "wout_li383_1.4m.nc"), ntheta=64, nzeta=64
    )
    coil = CoilSurface.from_uniform_offset(
        plasma, separation=0.25, ntheta=96, nzeta=96, mpol=18, ntor=18,
        standard_toroidal_angle=False, theta_reparameterization=None,
    )
    assert not coil.standard_toroidal_angle
    assert np.any(coil.numns != 0)

    # Independent computation over the physical toroidal angle phi.
    phis = np.linspace(0, 2 * np.pi, 400, endpoint=False)
    R, Z = coil.cross_section(phis)  # (nphi, ntheta) closed polygons at fixed phi
    R_next = np.roll(R, -1, axis=1)
    Z_next = np.roll(Z, -1, axis=1)
    # Shoelace cross-sectional area A(phi), then mean over phi -> minor radius.
    area_phi = 0.5 * np.abs(np.sum(R * Z_next - R_next * Z, axis=1))
    minor_ref = np.sqrt(area_phi.mean() / np.pi)
    # Volume = int_0^2pi [ oint (1/2) R^2 dZ ] dphi  (Green's theorem, physical phi).
    loop_int = 0.5 * np.sum(0.5 * (R**2 + R_next**2) * (Z_next - Z), axis=1)
    volume_ref = abs(loop_int.mean() * 2 * np.pi)
    major_ref = volume_ref / (2 * np.pi**2 * minor_ref**2)

    np.testing.assert_allclose(coil.minor_radius, minor_ref, rtol=3e-3)
    np.testing.assert_allclose(coil.volume, volume_ref, rtol=3e-3)
    np.testing.assert_allclose(coil.major_radius, major_ref, rtol=3e-3)
    np.testing.assert_allclose(coil.aspect_ratio, major_ref / minor_ref, rtol=3e-3)


def test_uniform_offset_scalars_invariant_to_toroidal_angle_representation():
    """`CoilSurface.from_uniform_offset(..., standard_toroidal_angle=True)` and
    `standard_toroidal_angle=False` build the *same physical* offset surface,
    represented two ways: the first root-solves so `zeta == phi` (nu == 0), the
    second labels the moved points by the plasma's `(theta, zeta)` and carries
    the toroidal shift in `nu`. All geometric scalars (area, volume, and the
    three radii) must therefore agree. They are not bit-identical because the
    two representations Fourier-truncate different functions at the same
    `mpol`/`ntor`; the residual is truncation error and shrinks ~4x per +8
    modes (checked separately), so a modest resolution matches to <2e-3."""

    plasma = PlasmaSurface.from_wout(
        str(EQUILIBRIA / "wout_d23p4_tm.nc"), ntheta=128, nzeta=128
    )
    common = dict(
        separation=0.3, ntheta=128, nzeta=128, mpol=24, ntor=24,
        theta_reparameterization="uniform_arclength",
    )
    coil_std = CoilSurface.from_uniform_offset(
        plasma, standard_toroidal_angle=True, **common
    )
    coil_nu = CoilSurface.from_uniform_offset(
        plasma, standard_toroidal_angle=False, **common
    )
    assert coil_std.standard_toroidal_angle
    assert not coil_nu.standard_toroidal_angle and np.any(coil_nu.numns != 0)

    for name in ["area", "volume", "minor_radius", "major_radius", "aspect_ratio"]:
        np.testing.assert_allclose(
            getattr(coil_nu, name), getattr(coil_std, name), rtol=1e-7,
            err_msg=f"{name} differs between nu and standard-angle representations",
        )


def test_cross_section_circular_torus_matches_analytic(nfp=3, R0=5.0, a=1.2):
    """For a plain circular torus, `zeta` already is the physical toroidal
    angle, so cross_section(phi) at any phi should reproduce the exact
    circular cross section (independent of theta-grid resolution)."""
    torus = FourierSurface.circular_torus(R0=R0, a=a, nfp=nfp, ntheta=32, nzeta=16)
    phi = np.array([0.0, 0.3, 1.5, 4.2, 2 * np.pi - 0.01])
    R, Z = torus.cross_section(phi)

    assert R.shape == (len(phi), torus.ntheta)
    assert Z.shape == (len(phi), torus.ntheta)
    # theta values on the grid, in some order, since interpolation at the
    # exact theta grid values (phi is an exact grid zeta) should reproduce
    # them to high precision.
    expected_R = np.sort(R0 + a * np.cos(torus.theta))
    expected_Z = np.sort(a * np.sin(torus.theta))
    for i in range(len(phi)):
        np.testing.assert_allclose(np.sort(R[i]), expected_R, atol=1e-8)
        np.testing.assert_allclose(np.sort(Z[i]), expected_Z, atol=1e-8)


def test_cross_section_default_phi_is_half_field_period():
    torus = FourierSurface.circular_torus(R0=5.0, a=1.0, nfp=4, ntheta=9, nzeta=8)
    R, Z = torus.cross_section()
    assert R.shape == (4, torus.ntheta)


def test_cross_section_nonstandard_toroidal_angle_matches_atan2():
    """A CoilSurface built by `from_uniform_offset(standard_toroidal_angle=False)`
    has a nonzero nu, so a constant-zeta slice is not a constant-phi cross
    section (ADR-025/ADR-026); cross_section must still return the surface's
    actual atan2(y, x) == phi points, not the naive constant-zeta slice."""

    plasma = PlasmaSurface.from_wout(
        str(EQUILIBRIA / "wout_li383_1.4m.nc"), ntheta=13, nzeta=12,
    )
    coil = CoilSurface.from_uniform_offset(
        plasma, separation=0.3, ntheta=13, nzeta=12, mpol=6, ntor=5,
        standard_toroidal_angle=False,
    )
    assert coil.standard_toroidal_angle is False
    assert np.any(coil.numns != 0)

    phi = np.array([0.0, 0.7])
    R, Z = coil.cross_section(phi)
    X = R * np.cos(phi)[:, None]
    Y = R * np.sin(phi)[:, None]
    # Every returned point must actually sit at physical angle phi (up to
    # interpolation error), i.e. atan2(Y, X) == phi.
    recovered_phi = np.arctan2(Y, X)
    for i in range(len(phi)):
        np.testing.assert_allclose(
            np.mod(recovered_phi[i] - phi[i] + np.pi, 2 * np.pi) - np.pi,
            0.0, atol=1e-6,
        )


def test_evaluate_at_matches_grid_evaluate():
    """`FourierSurface.evaluate_at` (arbitrary paired points) must agree with
    `_evaluate` (tensor-product grid) at the same points."""
    surf = FourierSurface.circular_torus(R0=5.0, a=1.0, nfp=3, ntheta=8, nzeta=9)
    theta_grid = surf.theta
    zeta_grid = surf.zeta
    tt, zz = np.meshgrid(theta_grid, zeta_grid, indexing="ij")

    pointwise = surf.evaluate_at(tt.ravel(), zz.ravel())
    grid = surf._evaluate(theta_grid, zeta_grid)

    np.testing.assert_allclose(
        pointwise["r"].reshape(3, surf.ntheta, surf.nzeta), grid["r"], atol=1e-12
    )
    np.testing.assert_allclose(
        pointwise["drdtheta"].reshape(3, surf.ntheta, surf.nzeta), grid["drdtheta"], atol=1e-12
    )
    np.testing.assert_allclose(
        pointwise["drdzeta"].reshape(3, surf.ntheta, surf.nzeta), grid["drdzeta"], atol=1e-12
    )


@pytest.mark.parametrize("standard_toroidal_angle", [True, False])
def test_evaluate_columns_matches_evaluate_at(standard_toroidal_angle):
    """`_evaluate_columns` is the fast path for a theta that varies with zeta
    (what a theta reparameterization produces); it must agree with the general
    `evaluate_at` on the same points, including the nonzero-nu case."""
    plasma = PlasmaSurface.circular_torus(R0=5.0, a=1.0, nfp=3, ntheta=9, nzeta=8)
    surf = CoilSurface.from_uniform_offset(
        plasma, separation=0.3, ntheta=9, nzeta=8, mpol=5, ntor=4,
        standard_toroidal_angle=standard_toroidal_angle,
    )
    zeta = np.array([0.0, 0.35, 0.9, 1.7])
    # A different theta in each zeta column, which is the whole point.
    theta = np.array([0.0, 1.0, 2.5, 4.4])[:, None] + np.array([0.0, 0.1, -0.2, 0.3])[None, :]

    columns = surf._evaluate_columns(theta, zeta)
    paired = surf.evaluate_at(theta.ravel(), np.broadcast_to(zeta, theta.shape).ravel())

    for key in ("r", "drdtheta", "drdzeta"):
        np.testing.assert_allclose(
            columns[key], paired[key].reshape((3,) + theta.shape), atol=1e-12
        )


def test_evaluate_columns_default_uses_evaluate_at():
    """The `Surface` default is `evaluate_at` on the flattened points; a
    representation that cannot do better inherits it unchanged."""
    surf = FourierSurface.circular_torus(R0=5.0, a=1.0, nfp=2, ntheta=8, nzeta=8)
    zeta = np.array([0.2, 0.8])
    theta = np.array([[0.1, 0.4], [1.5, 2.0], [3.0, 3.3]])

    np.testing.assert_allclose(
        Surface._evaluate_columns(surf, theta, zeta)["r"],
        surf._evaluate_columns(theta, zeta)["r"],
        atol=1e-12,
    )


def test_evaluate_at_derivatives_match_finite_differences_nonstandard_angle():
    """Same check as above, but for a surface with nonzero nu (nonstandard
    toroidal angle), where the derivative formulas have extra terms."""

    plasma = PlasmaSurface.circular_torus(R0=5.0, a=1.0, nfp=3, ntheta=9, nzeta=8)
    coil = CoilSurface.from_uniform_offset(
        plasma, separation=0.3, ntheta=9, nzeta=8, mpol=5, ntor=4,
        standard_toroidal_angle=False,
    )
    theta = np.array([0.3, 1.2, 2.5, 4.0])
    zeta = np.array([0.1, 0.4, 0.9, 1.3])
    eps = 1e-6

    base = coil.evaluate_at(theta, zeta)
    dtheta = coil.evaluate_at(theta + eps, zeta)
    dzeta = coil.evaluate_at(theta, zeta + eps)

    np.testing.assert_allclose(
        (dtheta["r"] - base["r"]) / eps, base["drdtheta"], atol=1e-4
    )
    np.testing.assert_allclose(
        (dzeta["r"] - base["r"]) / eps, base["drdzeta"], atol=1e-4
    )
